# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb0df39a5a19c53ab76fd48ac50462d64b5d4519d7d217f5253f57b2aa27ca050be872851c88d66a86c78f6af8d762ee040f59ae48495cebfd456d7227820cc0

test:
  secret_key_base: c32c370a20a5a6bbca58e547854a36d247102044268339f29fe25a7c76dbc89c66e993ae651df57046ce3427f51bdf30853cc69c9d8298ca25ae393005127400

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
